import "./globals.css"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import { NuqsAdapter } from "nuqs/adapters/next/app"

import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { Toaster } from "@/components/ui/sonner"
import { Providers } from "./providers"
import LoadTimeTracker from "@/components/LoadTime"

const inter = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
	title: "FarmPreneur",
	description: "Generated by create next app"
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<NuqsAdapter>
					<Providers>{children}</Providers>
					<Toaster richColors className={inter.className} />
				</NuqsAdapter>
				{/* <LoadTimeTracker /> */}
			</body>
		</html>
	)
}
