import "./globals.css"

import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { SessionProvider } from "next-auth/react"

import { auth } from "@/auth"
import ThemeProvider from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"

const inter = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Farm2go",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body className={inter.className}>
        <script
          async
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_PLACES_API_KEY}&libraries=places`}
        ></script>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
